# Site title and subtitle. This is used in _includes/header.html
title: 'Mediachain'
subtitle: 'an open, universal media library'

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# URL to source code, used in _includes/footer.html
codeurl: 'https://mediachain.io'

# Default categories (in order) to appear in the navigation
sections: [
    ['about', 'Mediachain'],
    ['setup', 'Installation and Setup'],
    ['usage', 'Using Mediachain'],
    ['publishing', 'Publishing Data'],
    ['tutorial', 'Tutorials'],
    ['arch', 'Mediachain Architecture']
]

collections:
  docs:
    output: true
    permalink: /:path

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
